myMovieSite/account/urls.py
from django.urls import path,re_path
from . import views
from django.urls import include

#你这个app 最好就做成这样，最多再添加一个修改密码的页面
#懂了没 懂啦 index拆分出去是啥
# 就是现在index归属在account这个app里面 但是实际上index和account没什
# 但是为了访问是 127.0.0.1/login这样来登陆 现在就只能写成这样
# 拆分后就是 127.0.0.1 是首页 127.0.0.1/account/login 这样是登陆
# 暂时就这样 还是比较好看的 127.0.0.1 首页 127.0.0.1/login 登陆 127.0.0.1/regist 注册
#懂了没 嗯嗯
# 你去下个模板 现在就可以开始套上了 前端吗 嗯 就有个网站叫模板之家 你去上面找个符合你主题的 比如搜电影 o'k'k
urlpatterns = [
    path('login',views.login,name='login'),
    path('register',views.register,name = 'register'),
    path('',views.index,name = 'index'),
    # path('details',views.details,name='details')
    # re_path(r'^details/(?P<id>[0-9]{4})/$',views.details,name = 'details'),
    re_path(r'^details/[(,)]*(?P<id>[0-9]{4})*/$',views.details,name = 'details'),
    path('update_comment', views.update_comment, name='update_comment'),
    #path(r'^search/', include('haystack.urls'))
    path('collect',views.collect,name = 'collect'),
    path('rating',views.rating,name = 'rating'),
    path('center',views.center,name = 'center'),
    path('logout',views.logout,name ='logout'),
   #re_path(r'^type/[\u4e00-\u9fa5]{2}/$',views.type,name = 'type')
    re_path(r'type/[(,)]*([\u4E00-\u9FA5]{2,4})*/$',views.type,name = 'type'),
   ##发送邮件
    path('email/',views.email,name='email'),
    path('send_verification/',views.send_verification,name='send_verification'),
    ##重置密码（接受邮件中url的参数）
    path('repsw/',views.repsw,name='repsw')

]
app_name = 'account'

myMovieSite/myMovieSite/urls.py
from django.urls import path
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url





from django.conf.urls import url
from django.contrib import admin
from django.urls import include #为什么不# import MySearchView

urlpatterns = [
    url('admin/', admin.site.urls),
    url('', include("account.urls")), #引入了account里面你写的url文件 到时候改就可以直接改account里面的urls.py
    url(r'^search/',include('haystack.urls')),

]

myMovieSite/account/models.py
from django.db import models
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
class users(models.Model):
    user_name = models.CharField(max_length=10,verbose_name='用户名')
    user_password = models.CharField(max_length=10)
    user_email = models.EmailField(unique=True)
    user_collection = models.CharField(max_length=200)
class EmailRecord(models.Model):
    code = models.CharField(max_length=30)
    email = models.EmailField(unique=True)

class movies(models.Model):
    ch_title = models.CharField(max_length=100)
    en_title = models.CharField(max_length=100)
    sector = models.CharField(max_length=100)
    actor = models.CharField(max_length=100)
    time = models.CharField(max_length=20)
    type = models.CharField(max_length=50)
    pic = models.CharField(max_length=100)
class collections(models.Model):
    user_name = models.CharField(max_length=10,verbose_name='用户名')
    mov_id = models.IntegerField(null=True)
class rate(models.Model):
    user_name = models.CharField(max_length=10, verbose_name='用户名')
    mov_id = models.IntegerField(null=True)
    rate = models.CharField(max_length=50,null=True)

class comments(models.Model):
    movie_id = models.IntegerField()
    user_name = models.CharField(max_length=50)
    co_time = models.DateTimeField(auto_now_add=True)
    co_text = models.TextField(default='')

myMovieSite/account/forms.py
from django import forms
from django.contrib.contenttypes.models import ContentType
from django.db.models import ObjectDoesNotExist
from ckeditor.widgets import CKEditorWidget

class Commentforms(forms.Form):
    movie_id = forms.IntegerField(widget=forms.HiddenInput)
    user = forms.CharField(widget=forms.HiddenInput)
    text = forms.CharField(widget=CKEditorWidget(config_name='comment_ckeditor'))
class ForgetForm(forms.Form):
    email = forms.EmailField(label='邮箱', widget=forms.TextInput(
        attrs={"class": "form-control", "placeholder": "请输入邮箱账号", "value": ""}),
                             max_length=100, error_messages={"required": "邮箱不能为空", "invalid": ""})
    verification_code = forms.CharField(
        label="验证码",
        widget=forms.TextInput(attrs={'class':'form-control','placeholder':'填写邮箱接受到的验证码'})
    )
    newpwd = forms.CharField(label='新密码', widget=forms.PasswordInput(
        attrs={'class':'form-control',"placeholder": "请输入新密码"}
    ))

myMovieSite/account/views.py
# Create your views here.
from django.shortcuts import redirect
from django.shortcuts import get_object_or_404, render
from django.http import JsonResponse
from django.core.paginator import Paginator, PageNotAnInteger, InvalidPage,EmptyPage
from django.template.defaulttags import register#为了使用range
from haystack.views import SearchView
from .models import movies, EmailRecord
from django import forms
from django.shortcuts import render,reverse
import string
import random
from django.http import HttpResponseRedirect,HttpResponse
from django.utils.timezone import localtime
from haystack.views import SearchView
import myMovieSite.settings
from django.db import models
from .models import users,rate
from .models import collections
from .models import comments
from .forms import Commentforms, ForgetForm
from django.http import JsonResponse
from django.db.models import Count, Q, Avg
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.hashers import make_password
from django.core.mail import send_mail
from django.views.decorators.csrf import csrf_exempt

@register.filter
def get_range(value):
    return range(value)
'''
def BlogIndex(request):
    blog_list = BlogsPost.objects.order_by('-date')
    blognum = list(range(1,(BlogsPost.objects.count())//11+2))  #每10篇博客分一页
    return render(request,'blog/index.html',{'blog_list':blog_list,'blog_num':blognum})
def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    template = loader.get_template('polls/index.html')
    context = {
        'latest_question_list': latest_question_list,
    }
    return HttpResponse(template.render(context, request))
'''
def register(request):
    while request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        email = request.POST.get('email')
        em=users.objects.filter(user_email=email)
        if em:
            return HttpResponse("zhuceshibai")
        user = users.objects.create()
        user.user_name = username
        user.user_password = password
        user.user_email = email
        user.save()
        return HttpResponseRedirect(reverse('account:index'))


    return render(request, 'account/register.html')







def login(request):
    while request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        referer = request.META.get('HTTP_REFERER','account/index.html')
        if email and password:
            email=email.strip()
            # 获取表单用户密码
            # 获取的表单数据与数据库进行比较
            user = users.objects.filter(user_email=email, user_password=password).first()
            if user:
                response=redirect(request.GET.get('from','account:index'))
                response.set_cookie('username', max_age=7 * 24 * 3600)
                request.session['islogin'] = True
                request.session['user'] = user.user_name
                return response
            else:
                return HttpResponse('yonghubucunzai')
        else:
            return HttpResponse('email password feizhen')
    return render(request, 'account/login.html')



def index(request):
    movies_list=movies.objects.all().order_by("id")#按中文标题排序
    types= ['科幻','动作','剧情','喜剧','家庭','动画']
    objs=collections.objects.values('mov_id').annotate(usercount = Count('user_name'))
    avg_rate = rate.objects.values('mov_id').annotate(avg_rate=Avg('rate'))
    movs={}
    l=[]
    for obj in objs:
        l.append((obj['usercount'],obj['mov_id']))
    sors = dict(sorted(l)[:3])
    values= sors.values()
    val = list(values)
    #for value in values:
    #for i in range(2):
    fav_movies=movies.objects.filter(Q(id = val[0])|Q(id = val[1]))
    #fav_movies_list= index.objects.raw('SELECT COUNT(*),movie_id FROM collections GROUP BY movie_id')
    paginator = Paginator(movies_list,4)
    page = request.GET.get('page')
    try:
        mov = paginator.page(page)
        # todo: 注意捕获异常
    except PageNotAnInteger:
            # 如果请求的页数不是整数, 返回第一页。
        mov = paginator.page(1)
    except InvalidPage:
            # 如果请求的页数不存在, 重定向页面
        return HttpResponse('找不到页面的内容')


    return render(request, 'account/index.html', {'movies_list': movies_list,'mov': mov,'fav_movies':fav_movies,'types':types,'avg_rate':avg_rate})


def type(request,type):
    movies_list = movies.objects.filter(type__contains = type)
    paginator = Paginator(movies_list, 4)
    page = request.GET.get('page')
    try:
        mov = paginator.page(page)
        # todo: 注意捕获异常
    except PageNotAnInteger:
        # 如果请求的页数不是整数, 返回第一页。
        mov = paginator.page(1)
    except InvalidPage:
        # 如果请求的页数不存在, 重定向页面
        return HttpResponse('找不到页面的内容')

    return render(request, 'account/index.html', {'movies_list': movies_list, 'mov': mov,})


def details(request,id):
    # 视图函数，返回文章详情页
    movie = movies.objects.filter(id=id).first()
    cmts = comments.objects.filter(movie_id = id)
    if request.session.has_key('islogin'):
        # 已经登录的用户，则放行
        context = {}
        context['user'] = request.session['user']
        context['curr_movie'] = movie
        context['id'] = id
        context['cmts'] = cmts
        # context['cookie'] = cookie

        context['comment_form'] = Commentforms(initial={'user': request.session['user'], 'movie_id': id})

        # user=users.object.filter()
        # comment= comments.objects.filter(mov_name=movie.ch_title,user_name=user)
        response = render(request, 'account/details.html', context)
        return response
    else:
        # 没有登录的用户，跳转到登录页面
        context = {}
        context['curr_movie'] = movie
        context['cmts'] = cmts
        response = render(request, 'account/details-un.html', context)
        return response
        # cookie = False

def rating(request):
    if request.method == "POST":
        mov_id = request.POST.get('mov_id')
        rat = request.POST.get('rate')
        if request.session.has_key('islogin'):
            user_name = request.session.get('user')
            object = rate.objects.filter(user_name=user_name,mov_id = mov_id)
            ra = float(rat)
            if object:

                if (ra <= 5):
                   object.rate = rat
                   return JsonResponse({'result': 'success', 'message': '评价成功'})
                else:
                    return JsonResponse({'result': 'fail', 'message': '评价失败'})
            else:
                if (ra <= 5):
                    obj = rate(mov_id=mov_id, rate=rat,user_name=user_name)
                    obj.save()
                    return JsonResponse({'result': 'success', 'message': '评价成功'})
                else:
                    return JsonResponse({'result': 'fail', 'message': '评价失败'})




def collect(request):
    #referer = request.META.post('HTTP_REFERER','account:index')
    if request.method == "POST":
        mov_id = request.POST.get('mov_id')
        if request.session.has_key('islogin'):
            user_name = request.session.get('user')
        # name_id = str(BlogUser.objects.get(name=name).id)
        # thisarticle = get_object_or_404(Articles, id=blog_id)
        # thisarticle.increase_views()
            #data = {}
            if collections.objects.filter(mov_id=mov_id).count() == 1:
            # 如果记录已经存在，则表示用户取消收藏
                exist_records=collections.objects.filter(mov_id=mov_id)
                exist_records.delete()
                return JsonResponse({'result':'fail', 'message':'取消收藏'})


            else:
                obj = collections(mov_id=mov_id, user_name=user_name)
                obj.save()
                return JsonResponse({'result': 'success', 'message':'收藏'})
        else:
           return render(request, 'account/login.html')



def update_comment(request):
    #referer = request.META.post('HTTP_REFERER','account:index')
    #movie_id = int(request.POST.get('object_id', ''))'
    comment_form = Commentforms(request.POST)
    data = {}
    if comment_form.is_valid():
        comment = comments()
        #comment.user_name = users.objects.filter(user_name=request.session['user'])[0]
        comment.user_name = comment_form.cleaned_data['user']
        comment.co_text = comment_form.cleaned_data['text']
        comment.movie_id = comment_form.cleaned_data['movie_id']
        #comment.content_type= comments.objects.filter(content_type = comment_form.cleaned_data['content_type'])[0]
        comment.save()


        data['status']='SUCCESS'
        data['user_name'] = comment.user_name
        data['co_time'] = localtime(comment.co_time.strftime('%d/%m/%Y %H:%M'))
        data['co_text'] = comment.co_text
        return JsonResponse(data)
    else:
        data['status'] = 'ERROR'
        return JsonResponse(data)



def center(request):
    if request.session.has_key('islogin'):
        user=request.session['user']
        col_mov = collections.objects.filter(user_name =user) # 按中文标题排序
        return render(request,"account/center.html",{"fav_movie":col_mov})
    else:
        return HttpResponseRedirect(reverse('account:login'))

def logout(request):
    del request.session['islogin']
    return HttpResponseRedirect(reverse('account:index'))


def email(request):
    form = ForgetForm(request.POST)
    if request.method == 'POST':
        email = form.cleaned_data['email']
        #user_email = users.objects.filter(user_email=email)
        #if user_email:
         #   send_mail(email, "forget")

    return render(request, 'account/email.html', locals())

def send_verification(request):
    email=request.GET.get('email')
    data={}
    if email !='':
        code = ''.join(random.sample(string.ascii_letters + string.digits,4))
        request.session['email_code'] = code
        send_mail(
                   '修改密码',
                   '验证码：%s' % code,
                   '3373319993@qq.com',

myMovieSite/account/templates/search/search.html
<!DOCTYPE HTML>
{% load static %}
<html>
	<head>
		<title>Home</title>
		<link rel="stylesheet" href="{% static 'account/css/bootstrap.css' %}">
        <link rel="stylesheet" href="{% static 'account/css/owl.carousel.css' %}">
		<link rel="stylesheet" href="{% static 'account/css/style.css' %}">
		<link rel="shortcut icon" href="{%static 'account/image/favicon.ico' %}" />
        <script src="{% static 'account/js/jquery.min.js' %}"></script>

	<!--<link href="{% static 'index/style/bootstrap.css' %}" rel="stylesheet" />
	<link href="css/bootstrap.css" rel='stylesheet' type='text/css' />
		<link href="css/owl.carousel.css" rel='stylesheet' type='text/css' />
		<link href="css/style.css" rel='stylesheet' type='text/css' />-->
		 <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
		 <!--<script src="js/jquery.min.js"></script>-->
		 <!-- Custom Theme files -->

		<meta name="viewport" content="width=device-width, initial-scale=1">
		</head>
	<body>
		<!-- container -->
		<div class="header">
		<div class="container">
			<!-- header -->
				<!-- logo -->
				<div class="logo">
					<a href="{% url 'account:index' %}"><img src="{%static 'account/image/logo.png'%}" title="MOVIES" /></a>
				</div>
				<!-- logo -->
				<!-- top-nav -->
				<div class="top-nav">
					<span class="menu"> </span>
					<ul>
						<li class="active"><a href="{% url 'account:index' %}">首页<span> </span></a></li>
						<li><a href="{% url 'account:login' %}">登陆</a></li>
						<li><a href="{% url 'account:register' %}">注册</a></li>
						<li><a href="{% url 'account:index' %}">关于我们</a></li>
						<li><a href="{% url 'account:center' %}">我的收藏</a></li>
						<div class="clearfix"> </div>
					</ul>
				</div>
				<div class="clearfix"> </div>
				<!-- top-nav -->
				<!-- script-for-menu -->
				<script>
					$(document).ready(function(){
						$("span.menu").click(function(){
							$(".top-nav ul").slideToggle(200);
						});
					});
				</script>
				<!-- script-for-menu -->
			</div>
			<!-- header -->
		</div>
		<!-- banner -->
		<div class="banner">
			<!-- slider -->
				<!--- img-slider --->
				<div class="img-slider">
						<!----start-slider-script---->
					<script src="{% static 'account/js/responsiveslides.min.js' %}"></script>
					 <script>
					    // You can also use "$(window).load(function() {"
					    $(function () {
					      // Slideshow 4
					      $("#slider4").responsiveSlides({
					        auto: true,
					        pager: true,
					        nav: true,
					        speed: 500,
					        namespace: "callbacks",
					        before: function () {
					          $('.events').append("<li>before event fired.</li>");
					        },
					        after: function () {
					          $('.events').append("<li>after event fired.</li>");
					        }
					      });

					    });
					  </script>
					<!----//End-slider-script---->
					<!-- Slideshow 4 -->
					    <div  id="top" class="callbacks_container">
					      <ul class="rslides" id="slider4">
					        <li>
					          <img class="img-responsive" src="{%static 'account/image/slide1.jpg' %}" alt="">
					          <div class="slider-caption">
					          	<div class="slider-caption-inner">
						          	 <h1>movies<span>Z</span></h1>
						         	 <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sollicitudin lectus in quam elementum aliquet. Quisque gravida fringilla velit nec ornare. </p>
						         	 <a class="caption-btn" href="#">ReadMore</a>
					         	 </div>
					          </div>
					        </li>
					        <li>
					          <img  src="{% static 'account/image/slide2.jpg' %}" alt="">
					           <div class="slider-caption">
					          	 <div class="slider-caption-inner">
						          	 <h1>movie<span>Z</span></h1>
						         	 <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sollicitudin lectus in quam elementum aliquet. Quisque gravida fringilla velit nec ornare. </p>
						         	 <a class="caption-btn" href="#">ReadMore</a>
					         	 </div>
					          </div>
					        </li>
					        <li>
					          <img  src="{% static 'account/image/slide3.jpg' %}" alt="">
					           <div class="slider-caption">
					            <div class="slider-caption-inner">
						          	 <h1>movie<span>Z</span></h1>
						         	 <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sollicitudin lectus in quam elementum aliquet. Quisque gravida fringilla velit nec ornare. </p>
						         	 <a class="caption-btn" href="#">ReadMore</a>
					         	 </div>
					          </div>
					        </li>
					      </ul>
					    </div>
					    <div class="clearfix"> </div>
					</div>
						<!-- slider -->
		</div>
		<!-- banner -->
		<!-- categories#左侧类别框 -->
		<div class="categories">
			<div class="container">
				<div class="categories-left">
					<ul class="options">
						{% for type in types %}
						    <li><a href="{% url 'account:type' type %}">{{type}}</a>
                        {% endfor %}
					</ul>
					<select class="s-option">
						<option>select categories</option>
						<option>Adventure</option>
						<option>Adventure</option>
						<option>Adventure</option>
					</select>
				</div>
				<!--右侧搜索框!-->
				<div class="categories-right">
					<form action="/search" method="get">
						<input type="text" id="q" name="q" placeholder="Search here" required>
						<input type="submit" value="search" />
					</form>
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
		<!-- categories -->
		<div class="tlinks">Collect from <a href="https://www.google.com/" >在线GOOGLE</a></div>
		<!-- content -->
{% block content %}
        {% if query %}
            <h3>搜索结果</h3>

            {% for result in page.object_list %}
                <p>
                    <a href=''>{{ result.object.ch_title }}</a>
                </p>
            {% empty %}
                <p>No results found.</p>
            {% endfor %}

            {% if page.has_previous or page.has_next %}
                <div>
                    {% if page.has_previous %}<a href="?q={{ query }}&amp;page={{ page.previous_page_number }}">{% endif %}&laquo; Previous{% if page.has_previous %}</a>{% endif %}
                    |
                    {% if page.has_next %}<a href="?q={{ query }}&amp;page={{ page.next_page_number }}">{% endif %}Next &raquo;{% if page.has_next %}</a>{% endif %}
                </div>
            {% endif %}
        {% else %}
            {# Show some example queries to run, maybe query syntax, something else? #}
        {% endif %}
    </form>
{% endblock %}